version: 2.1

orbs:
  maven: circleci/maven@1.4.1
  codecov: codecov/codecov@4.0.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  test:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout

  upload-to-codecov:
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: "Tests with JaCoCo coverage"
          command: mvn clean verify jacoco:report
      - run:
          name: "Upload to Codecov"
          command: bash <(curl -s https://codecov.io/bash)
      - codecov/upload

workflows:
  maven_test:
    jobs:
      - build
      - maven/test:
          filters:
            branches:
              only:
                - master
      - upload-to-codecov:
          requires:
            - maven/test


name: Checkstyle Report

on:
  push:
    branches:
      - master

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Publish Checkstyle report
        uses: Juuxel/publish-checkstyle-report@v1
        if: ${{ failure() || success() }}
        with:

          reports: |
            target/site/checkstyle/*.xml
